
rocketmq:
  name-server: 47.96.111.179:9876
  producer:
    group: mq_p_group
    send-message-timeout: 5000
    retry-next-server: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Zxy921209
    url: jdbc:mysql://rm-bp18s2vkm33kn6fncwo.mysql.rds.aliyuncs.com:3306/mp_test?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false


mybatis:
  configuration:
    log-prefix: zxylog.print.
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  #config-location: classpath:mybatis.config.xml